#!/usr/bin/env node
'use strict';

const mirv    = require('./lib'),
      express = require('express'),
      path    = require('path'),
      fs      = require('fs');

mirv.semver.engine_satisfies('7.2');

function routes(app, config, logger) {
  const pkg = JSON.parse(fs.readFileSync(`${path.resolve(__dirname)}/package.json`));
  app.use(express.static(config.routes.ressources_path));
  app.get('/healthz', (req, res) => {
    res.json({ok:true}).end();
  });
  app.get('/version', (req, res) => {
    res.json({version:pkg.version}).end();
  });
}

const do_not_log_routes = ['/healthz'];
mirv.supervisor(mirv.rest(routes, do_not_log_routes), {routes:{ressources_path:process.argv[2] || '.'}});
